name: Render GitBook

on:
  push:
    branches:
      - master

    
jobs:
  
  windows:
    runs-on: windows-latest
    steps:
      - name: install Pandoc
        run: choco install pandoc
      - name: Checkout Repository
        uses: actions/checkout@master 
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install R packages with remotes
        run: |
          Rscript -e "install.packages('remotes', repos = 'https://muug.ca/mirror/cran/')"
          Rscript -e "remotes::install_deps()"
      - name: Build GitBook
        run: |-
          Rscript -e "options(bookdown.render.file_scope = FALSE); bookdown::render_book('index.Rmd', 'bookdown::gitbook')"